[package]
name = "tracey"
version = "0.1.0"
authors = ["Danny van Swieten <dannyvanswieten@gmail.com>"]
edition = "2018"

[dependencies]
renderer = {path = "../renderer"}
ui = {path = "../ui"}
winit = "*"
image = "*"
glm = "*"