[package]
name = "tracey"
version = "0.1.0"
authors = ["Danny van Swieten <dannyvanswieten@gmail.com>"]
edition = "2021"

[dependencies]
renderer = {path = "../renderer"}
vk_utils = {path = "../vk_utils"}
ash = "*"
image = "*"
nalgebra-glm = "*"
gltf = "*"
rand = "*"